name: Build and test

on:
  pull_request:
    branches: [ main ]
defaults:
  run:
    shell: bash
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      # PR builds don't checkout the commit by default, so we're going to correct that
      - name: checkout commit
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.300
      - name: setup local package feed
        run: mkdir LocalPackageSource

      # we use the bash shell for the following to so that path globbing works on windows
      - name: build and pack the Runtime
        shell: bash
        run: | 
          dotnet build Jackfruit.Runtime
          dotnet pack Jackfruit.Runtime
          dotnet nuget push Jackfruit.Runtime/bin/Debug/*.nupkg --source JackFruit
      
      - name: build and pack the Source Generator
        shell: bash
        run: |
          dotnet build Jackfruit.IncrementalGenerator
          dotnet pack Jackfruit.IncrementalGenerator
          dotnet nuget push Jackfruit.IncrementalGenerator/bin/Debug/*.nupkg --source JackFruit

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Packages (${{ matrix.os }})

          path: |
            Jackfruit.IncrementalGenerator/bin/Debug/*.nupkg
            Jackfruit.Runtime/bin/Debug/*.nupkg

